on:
  push:
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
        
      - run: flutter config --no-analytics
      
      - run: dart --disable-analytics
      
      - run: flutter pub get
      
      - run: flutter build windows
      
      - name: Build Installer
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "inno-setup.iss"
        shell: cmd
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Setup
          path: build/RevisionTool-Setup.exe
        
         
